"""empty message

Revision ID: 38769c39c499
Revises: dadc8c4a107b
Create Date: 2019-08-29 21:21:44.634929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38769c39c499'
down_revision = 'dadc8c4a107b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('IP', sa.String(50), nullable=True))
    op.add_column('user', sa.Column('logindate', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'logindate')
    op.drop_column('user', 'IP')
    # ### end Alembic commands ###
