"""empty message

Revision ID: 8f1ee0737c39
Revises: cef573cf8f0d
Create Date: 2019-08-29 08:40:58.737746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f1ee0737c39'
down_revision = 'cef573cf8f0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('intro', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'intro')
    # ### end Alembic commands ###
