"""empty message

Revision ID: dadc8c4a107b
Revises: 8f1ee0737c39
Create Date: 2019-08-29 21:08:22.575645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dadc8c4a107b'
down_revision = '8f1ee0737c39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('loginsum', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'loginsum')
    # ### end Alembic commands ###
